- name: deploy docker and docker-compose
  hosts: api
  connection: ssh
  become: True
  become_user: root

  tasks:
  - name: Update apt
    apt: update_cache=yes

  - name: update apt-get using traditional command
    action: shell apt-get update

  - name: install required basic packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - git
      - zip
      - unzip
      - wget
      - ca-certificates
      - lsb-release
      - gnupg
      - apt-show-versions
      - apt-transport-https
      - curl
      - python3-pip

  - name: Download the docker gpg file to Ubuntu
    ansible.builtin.command: /bin/mkdir -pv /etc/apt/keyrings
  
  - name: Add Docker and docker compose support to the Ubuntu's packages list
    ansible.builtin.command: /bin/echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-pluginsudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-pluginlinux/ubuntu   $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: update apt-get using traditional command
    action: shell apt-get update

  - name: get latest version of ops agent for monitoring log and metrics
    ansible.builtin.get_url:
      url: https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
      dest: /tmp
  
  - name: install docker and etc
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
 
  - name: install ops agent
    ansible.builtin.command: /bin/bash /tmp/add-google-cloud-ops-agent-repo.sh --also-install

  - name: run cloud ops agent service
    service:
      name: google-cloud-ops-agent
      enabled: true