version: "3.1"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      MYSQL_HOST: mysql:3306
      MYSQL_DATABASE: gogin
      GIN_MODE: test
      API_KEY: a568e7ffcbmshb9cfb3af67b3884p175b70jsn8b59b6c0763a
      API_HOST: weatherbit-v1-mashape.p.rapidapi.com
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.rule=Host(`localhost`)"
    #   - "traefik.http.routers.api.rule=Path(`/endpoint`)"
    #   - "traefik.http.routers.api.entrypoints=web"
  # traefik:
  #   image: traefik:v2.5
  #   ports:
  #     - 8082:8080
  #     - 81:80
  #   volumes:
  #     # - ./traefik.yml:/etc/traefik/traefik.yml
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   command:
  #     #- "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gogin
      MYSQL_USER: user 
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
networks:
  default:
    driver: bridge