version: "3.1"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      MYSQL_HOST: mysql:3306
      MYSQL_DATABASE: gogin
      GIN_MODE: test
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gogin
      MYSQL_USER: user 
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
networks:
  default:
    driver: bridge